apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-deployment
  labels:
    app: full
spec:
  replicas: 1
  selector:
    matchLabels:
      app: full
  template:
    metadata:
      labels:
        app: full
    spec:
      containers:
      - name: full
        image: full-twitchapp
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: full-service
spec:
  type: NodePort
  selector:
    app: full
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30008
