const EVENT_TYPES_URL_PARAMETER = 'eventTypes'
const PREVIEW_URL_PARAMETER = 'showTest'
const COOKIE_NAME = "TWITCH_COOKIE"

export {
  EVENT_TYPES_URL_PARAMETER,
  PREVIEW_URL_PARAMETER,
  COOKIE_NAME
}
