const EVENT_TYPES_URL_PARAMETER = 'eventTypes'
const PREVIEW_URL_PARAMETER = 'showTest'
const USER_COOKIE_NAME = "TWITCH_COOKIE"
const OPTIONS_COOKIE_NAME = "OPTIONS_COOKIE_NAME"

export {
  EVENT_TYPES_URL_PARAMETER,
  PREVIEW_URL_PARAMETER,
  USER_COOKIE_NAME,
  OPTIONS_COOKIE_NAME
}
