const EVENT_TYPES_URL_PARAMETER = 'eventTypes'
const PREVIEW_URL_PARAMETER = 'showTest'
const USER_COOKIE_NAME = 'TWITCH_COOKIE'
const ACTIVE_USER_COOKIE_NAME = 'ACTIVE_USER'
const OPTIONS_COOKIE_NAME = 'OPTIONS_COOKIE_NAME'

export {
  EVENT_TYPES_URL_PARAMETER,
  PREVIEW_URL_PARAMETER,
  USER_COOKIE_NAME,
  ACTIVE_USER_COOKIE_NAME,
  OPTIONS_COOKIE_NAME
}
